logging:
  level.: INFO
server:
  port: 8099   

management:
  security:
    enabled: false


projetoGenerico:
  environment-config: local    
          
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user:
    password:
  main:
    banner-mode: log
  datasource:    
    url: jdbc:mysql://localhost:3306/generic_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 5
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none          
        temp:
          use_jdbc_metadata_defaults: true
  batch:
    job:
      enabled: false
    initialize-schema: always